
---
- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    username: admin
	password: password   # Ideally we should add encrypted credetial in inventory
   
  tasks:

	- name: Allow external DNS call
	  fortios_ipv4_policy:
		id: 42
		src_addr: internal_network
		dst_addr: all
		service: dns
		nat: True
		state: present
		policy_action: accept
		logtraffic: disable

	- name: Public Web
	  fortios_ipv4_policy:
		id: 42
		src_addr: all
		dst_addr: webservers
		services:
		  - http
		  - https
		state: present
		policy_action: accept

	- name: Some Policy
	  fortios_ipv4_policy:
		id: 42
		comment: "no comment (created by ansible)"
		src_intf: vl1000
		src_addr:
		  - some_serverA
		  - some_serverB
		dst_intf:
		  - vl2000
		  - vl3000
		dst_addr: all
		services:
		  - HTTP
		  - HTTPS
		nat: True
		state: present
		policy_action: accept
		logtraffic: disable
	  tags:
		- policy
